const recipes = [
  {
    name: "Chicken Curry",
    description: "A flavorful Indian-style chicken curry with spices and a creamy tomato base.",
    ingredients: ["chicken thighs", "onion", "garlic", "ginger", "tomato puree", "yogurt", "garam masala", "cumin", "coriander"],
    instructions: ["Heat oil in a pot and sauté chopped onions until golden.", "Add garlic and ginger, cook for 1 minute. Stir in spices.", "Add chicken and cook until sealed.", "Stir in tomato puree and simmer for 15 minutes.", "Add yogurt, mix well, and cook for 10 more minutes.", "Serve with rice or naan."],
    imageUrl: "/images/recipeImage-chicken.jpg",
    cookingTime: 45,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Mac and Cheese",
    description: "Creamy baked macaroni with a crispy cheese topping.",
    ingredients: ["macaroni", "butter", "flour", "milk", "cheddar cheese", "salt", "pepper"],
    instructions: ["Cook macaroni according to package instructions.", "Make a roux with butter and flour. Slowly whisk in milk.", "Stir in shredded cheddar cheese until melted.", "Combine cheese sauce with cooked macaroni.", "Transfer to a baking dish, top with more cheese.", "Bake at 375°F for 20 minutes until golden."],
    imageUrl: "/images/recipeImage-mac.jpg",
    cookingTime: 35,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "French Toast",
    description: "Classic breakfast toast soaked in egg and milk, then pan-fried.",
    ingredients: ["bread", "eggs", "milk", "cinnamon", "vanilla extract", "butter"],
    instructions: ["Whisk eggs, milk, cinnamon, and vanilla in a shallow bowl.", "Dip bread slices into the mixture, coating both sides.", "Heat butter in a skillet and fry each slice until golden on both sides.", "Serve with syrup, fruit, or powdered sugar."],
    imageUrl: "/images/recipeImage-french.jpg",
    cookingTime: 15,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Baked Ziti",
    description: "A hearty Italian pasta bake with tomato sauce and melted cheese.",
    ingredients: ["ziti pasta", "ground beef", "onion", "garlic", "tomato sauce", "ricotta cheese", "mozzarella cheese", "parmesan"],
    instructions: ["Cook pasta and set aside. Sauté onion, garlic, and ground beef until browned.", "Stir in tomato sauce and simmer for 10 minutes.", "Layer pasta, meat sauce, ricotta, and mozzarella in a baking dish.", "Repeat layers and top with parmesan.", "Bake at 375°F for 25 minutes or until bubbly and golden."],
    imageUrl: "/images/recipeImage-baked.jpg",
    cookingTime: 40,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Shrimp Scampi",
    description: "Garlicky shrimp cooked in butter and white wine, served over pasta.",
    ingredients: ["shrimp", "garlic", "butter", "olive oil", "white wine", "lemon juice", "spaghetti"],
    instructions: ["Cook pasta and set aside.", "Sauté garlic in butter and olive oil until fragrant.", "Add shrimp and cook until pink.", "Pour in white wine and lemon juice, simmer for 3 minutes.", "Toss shrimp with pasta and serve with parsley."],
    imageUrl: "/images/recipeImage-shrimp.jpg",
    cookingTime: 20,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Stuffed Peppers",
    description: "Bell peppers filled with seasoned rice and ground beef, baked to perfection.",
    ingredients: ["bell peppers", "ground beef", "onion", "rice", "tomato sauce", "cheddar cheese"],
    instructions: ["Slice tops off peppers and remove seeds.", "Cook rice and set aside. Sauté onion and ground beef until browned.", "Mix beef with rice and half of the tomato sauce.", "Stuff peppers and place in a baking dish.", "Top with remaining sauce and cheese. Bake at 375°F for 25–30 minutes."],
    imageUrl: "/images/recipeImage-stuffed.jpg",
    cookingTime: 45,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Mushroom Risotto",
    description: "Creamy arborio rice cooked slowly with mushrooms and broth.",
    ingredients: ["arborio rice", "mushrooms", "onion", "garlic", "white wine", "vegetable broth", "parmesan"],
    instructions: ["Sauté onion, garlic, and mushrooms in olive oil.", "Add arborio rice and cook for 1 minute.", "Pour in white wine and let it absorb.", "Add warm broth gradually, stirring constantly until rice is tender.", "Stir in parmesan and serve creamy and hot."],
    imageUrl: "/images/recipeImage-mushroom.jpg",
    cookingTime: 35,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Egg Fried Rice",
    description: "Quick stir-fried rice with scrambled eggs and vegetables.",
    ingredients: ["rice", "eggs", "soy sauce", "green onions", "peas", "carrots", "sesame oil"],
    instructions: ["Scramble eggs in a wok and set aside.", "Sauté vegetables in sesame oil.", "Add cooked rice and stir-fry for 2–3 minutes.", "Add soy sauce and cooked eggs. Stir well.", "Garnish with green onions and serve hot."],
    imageUrl: "/images/recipeImage-egg.jpg",
    cookingTime: 20,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Quinoa Salad",
    description: "A refreshing salad with quinoa, veggies, and lemon vinaigrette.",
    ingredients: ["quinoa", "cucumber", "tomatoes", "red onion", "lemon", "olive oil", "parsley"],
    instructions: ["Cook quinoa and let cool.", "Chop vegetables and mix with quinoa.", "Whisk lemon juice with olive oil and salt.", "Toss salad with dressing and parsley.", "Serve chilled or at room temperature."],
    imageUrl: "/images/recipeImage-quinoa.jpg",
    cookingTime: 25,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Tuna Melt",
    description: "Toasted sandwich with tuna salad and melted cheese.",
    ingredients: ["bread", "canned tuna", "mayonnaise", "cheddar cheese", "onion", "black pepper"],
    instructions: ["Mix tuna with mayonnaise, chopped onion, and pepper.", "Spread mixture on bread and top with cheese.", "Top with another slice of bread and toast in a skillet or oven until golden and melted.", "Serve warm."],
    imageUrl: "/images/recipeImage-tuna.jpg",
    cookingTime: 15,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Falafel Wrap",
    description: "Crispy falafel wrapped in pita with vegetables and tahini sauce.",
    ingredients: ["falafel", "pita bread", "lettuce", "tomato", "cucumber", "tahini sauce"],
    instructions: ["Cook falafel until crispy.", "Warm pita bread and layer with lettuce, tomato, cucumber.", "Add falafel and drizzle with tahini sauce.", "Roll into a wrap and serve."],
    imageUrl: "/images/recipeImage-falafel.jpg",
    cookingTime: 20,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Omelette",
    description: "Fluffy eggs folded with cheese and vegetables.",
    ingredients: ["eggs", "milk", "bell pepper", "onion", "cheese", "butter", "salt", "pepper"],
    instructions: ["Whisk eggs with a splash of milk, salt, and pepper.", "Heat butter in a pan and sauté vegetables.", "Pour in eggs and cook gently.", "Add cheese, fold the omelette, and cook until set.", "Serve hot."],
    imageUrl: "/images/recipeImage-omelette.jpg",
    cookingTime: 10,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Grilled Chicken",
    description: "Juicy grilled chicken breasts marinated in herbs and lemon.",
    ingredients: ["chicken breasts", "lemon juice", "garlic", "olive oil", "oregano", "salt", "pepper"],
    instructions: ["Marinate chicken with lemon, garlic, oil, and herbs for 30 minutes.", "Grill on medium heat for 6–8 minutes per side.", "Let rest for 5 minutes before serving.", "Serve with salad or rice."],
    imageUrl: "/images/recipeImage-grilled.jpg",
    cookingTime: 30,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "BBQ Ribs",
    description: "Slow-cooked pork ribs with smoky barbecue flavor.",
    ingredients: ["pork ribs", "BBQ sauce", "salt", "pepper", "paprika"],
    instructions: ["Season ribs with salt, pepper, and paprika.", "Wrap in foil and bake at 300°F for 2.5 hours.", "Unwrap and brush with BBQ sauce.", "Broil for 5–10 minutes until caramelized.", "Let rest and serve."],
    imageUrl: "/images/recipeImage-bbq.jpg",
    cookingTime: 180,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Spaghetti Carbonara",
    description: "A creamy Italian pasta made with pancetta, eggs, and parmesan.",
    ingredients: ["spaghetti", "pancetta", "eggs", "parmesan cheese", "black pepper", "salt"],
    instructions: [
      "Boil spaghetti in salted water until al dente. Reserve 1/2 cup of pasta water before draining.",
      "In a bowl, whisk eggs with grated parmesan cheese and a pinch of black pepper.",
      "Cook pancetta in a large pan until crispy, then remove from heat.",
      "Add drained pasta to the pan with pancetta. Stir quickly to cool slightly.",
      "Add the egg and cheese mixture, stirring constantly. Use reserved pasta water to loosen the sauce if needed.",
      "Serve immediately with extra parmesan and black pepper.",
    ],
    imageUrl: "/images/recipeImage-spaghetti.jpg",
    cookingTime: 25,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Chicken Alfredo Pasta",
    description: "Creamy pasta tossed with sautéed chicken and homemade Alfredo sauce.",
    ingredients: ["fettuccine", "chicken breast", "butter", "garlic", "heavy cream", "parmesan cheese", "salt", "pepper"],
    instructions: [
      "Cook fettuccine according to package instructions.",
      "Slice chicken and season with salt and pepper. Cook in butter until golden and cooked through.",
      "In the same pan, add garlic and cook until fragrant. Add heavy cream and simmer for 3 minutes.",
      "Stir in grated parmesan cheese and let the sauce thicken.",
      "Combine pasta, chicken, and sauce. Toss well to coat.",
      "Serve hot with extra parmesan on top.",
    ],
    imageUrl: "/images/recipeImage-chicken-alf.jpg",
    cookingTime: 30,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Classic Margherita Pizza",
    description: "A traditional Neapolitan pizza topped with tomatoes, mozzarella, and basil.",
    ingredients: ["pizza dough", "tomato sauce", "fresh mozzarella", "fresh basil", "olive oil", "salt"],
    instructions: ["Preheat oven to 475°F (245°C) with a pizza stone inside.", "Stretch pizza dough into a 10–12 inch circle.", "Spread a thin layer of tomato sauce over the dough.", "Tear mozzarella into pieces and distribute over the sauce.", "Bake for 10–12 minutes or until crust is golden and cheese is bubbling.", "Top with fresh basil leaves and a drizzle of olive oil before serving."],
    imageUrl: "/images/recipeImage-classic.jpg",
    cookingTime: 20,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Beef Tacos",
    description: "Spicy ground beef in crispy taco shells with your favorite toppings.",
    ingredients: ["ground beef", "taco seasoning", "taco shells", "lettuce", "cheddar cheese", "salsa"],
    instructions: ["Cook ground beef in a skillet over medium heat until browned.", "Add taco seasoning and 1/4 cup of water. Simmer for 5 minutes.", "Warm taco shells according to package instructions.", "Fill each shell with beef, shredded lettuce, cheese, and salsa.", "Serve immediately with extra toppings if desired."],
    imageUrl: "/images/recipeImage-beef.jpg",
    cookingTime: 20,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Vegetable Stir-Fry",
    description: "A quick, colorful stir-fry with a savory soy-based sauce.",
    ingredients: ["broccoli", "carrot", "bell pepper", "soy sauce", "garlic", "cornstarch", "sesame oil"],
    instructions: ["Chop all vegetables into bite-sized pieces.", "Heat sesame oil in a large wok or skillet. Add garlic and stir-fry for 30 seconds.", "Add vegetables and stir-fry for 5–7 minutes until tender-crisp.", "Mix soy sauce with a bit of cornstarch and water. Pour over vegetables.", "Cook for another 2 minutes until sauce thickens.", "Serve hot over rice or noodles."],
    imageUrl: "/images/recipeImage-vegetable.jpg",
    cookingTime: 15,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Tomato Basil Soup",
    description: "Rich, comforting soup with roasted tomatoes and fresh basil.",
    ingredients: ["ripe tomatoes", "onions", "garlic", "vegetable broth", "basil", "olive oil", "salt", "pepper"],
    instructions: ["Cut tomatoes in half and roast with garlic and onions at 400°F for 25 minutes.", "Transfer roasted ingredients to a pot and add vegetable broth.", "Simmer for 15 minutes, then blend until smooth.", "Stir in chopped fresh basil, season with salt and pepper.", "Simmer for 5 more minutes and serve hot."],
    imageUrl: "/images/recipeImage-tomato.jpg",
    cookingTime: 40,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Grilled Cheese Sandwich",
    description: "Golden brown crispy sandwich with gooey melted cheese.",
    ingredients: ["bread slices", "butter", "cheddar cheese"],
    instructions: ["Butter one side of each bread slice.", "Place cheese between unbuttered sides.", "Cook in a skillet over medium heat until golden brown, flipping halfway.", "Slice and serve hot."],
    imageUrl: "/images/recipeImage-grilled-che.jpg",
    cookingTime: 10,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Avocado Toast",
    description: "Crunchy toast topped with seasoned mashed avocado.",
    ingredients: ["bread slices", "ripe avocado", "lemon juice", "salt", "chili flakes"],
    instructions: ["Toast bread slices until golden and crisp.", "Mash avocado in a bowl with lemon juice and salt.", "Spread avocado on toast and sprinkle with chili flakes.", "Serve immediately."],
    imageUrl: "/images/recipeImage-avocado.jpg",
    cookingTime: 5,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Lemon Garlic Salmon",
    description: "Flaky oven-baked salmon with lemon and garlic butter.",
    ingredients: ["salmon fillets", "lemon", "garlic", "butter", "parsley", "salt", "pepper"],
    instructions: ["Preheat oven to 375°F (190°C).", "Place salmon fillets on a lined baking sheet.", "Melt butter and mix with minced garlic and lemon juice. Brush over salmon.", "Season with salt and pepper. Bake for 15–18 minutes.", "Garnish with chopped parsley and lemon slices. Serve hot."],
    imageUrl: "/images/recipeImage-lemon.jpg",
    cookingTime: 20,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
  {
    name: "Banana Pancakes",
    description: "Fluffy pancakes with sweet mashed banana mixed in.",
    ingredients: ["flour", "banana", "milk", "egg", "baking powder", "sugar", "butter"],
    instructions: ["Mash bananas in a large bowl. Add milk, egg, and melted butter. Mix well.", "Whisk in flour, sugar, and baking powder until smooth.", "Heat a nonstick pan and pour batter in small rounds.", "Cook until bubbles form, then flip and cook until golden.", "Serve warm with maple syrup or fruit."],
    imageUrl: "/images/recipeImage-banana.jpg",
    cookingTime: 15,
    author: "68670ea8b0a9a2c8bfcd8f94",
    averageRating: 0,
    numReviews: 0,
  },
];

module.exports = recipes;
